version: "3"

services:
  golang:
    tty: true
    build: "./app"
    volumes:
      - ./app:/go/src/github.com/docker_go_nginx/app
    ports:
      - "3000"
    command: bash -c "cd app && realize start --server"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "golang"
  db: 
    image: mysql:5.7.22
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: racmy 
      MYSQL_PASSWORD: racmy
      MYSQL_DATABASE: book-management 
